---
- hosts: all 
  gather_facts: yes
  become: yes
  become_user: root
  vars_files:
    - vars/common.yml
    - vars/{{ deployment_environment }}/ansible.yml
    - vars/jannaten


  roles:
    - installation-apache
    - config-host
